#!/bin/bash
#
# Setup Nginx reverse proxy with optional SSL via Certbot
# This script installs nginx and configures it to proxy to the GameHaven app
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'
BOLD='\033[1m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/.."

echo ""
echo -e "${CYAN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}          ${BOLD}Nginx Reverse Proxy Setup${NC}                         ${CYAN}║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Load config if available
if [ -f .env ]; then
    # shellcheck disable=SC1091
    source .env
fi

# Prompt for domain
read -p "$(echo -e "${BLUE}?${NC} Enter your domain name (e.g., games.example.com): ")" DOMAIN

if [ -z "$DOMAIN" ]; then
    echo -e "${RED}Error: Domain is required${NC}"
    exit 1
fi

# Get app port
APP_PORT=${APP_PORT:-3000}
read -p "$(echo -e "${BLUE}?${NC} App port [${APP_PORT}]: ")" INPUT_PORT
APP_PORT=${INPUT_PORT:-$APP_PORT}

# Ask about SSL
read -p "$(echo -e "${BLUE}?${NC} Setup SSL with Let's Encrypt? (y/n) [y]: ")" SETUP_SSL
SETUP_SSL=${SETUP_SSL:-y}

# Detect package manager
if command -v apt-get &> /dev/null; then
    PKG_MGR="apt"
elif command -v dnf &> /dev/null; then
    PKG_MGR="dnf"
elif command -v yum &> /dev/null; then
    PKG_MGR="yum"
else
    echo -e "${RED}Error: Unsupported package manager. Please install nginx manually.${NC}"
    exit 1
fi

echo ""
echo -e "${BOLD}━━━ Installing Nginx ━━━${NC}"
echo ""

# Install nginx
if ! command -v nginx &> /dev/null; then
    echo -e "${CYAN}Installing nginx...${NC}"
    if [ "$PKG_MGR" = "apt" ]; then
        sudo apt-get update
        sudo apt-get install -y nginx
    elif [ "$PKG_MGR" = "dnf" ]; then
        sudo dnf install -y nginx
    else
        sudo yum install -y nginx
    fi
    echo -e "${GREEN}✓${NC} Nginx installed"
else
    echo -e "${GREEN}✓${NC} Nginx already installed"
fi

# Create nginx config
echo ""
echo -e "${BOLD}━━━ Configuring Nginx ━━━${NC}"
echo ""

NGINX_CONF="/etc/nginx/sites-available/gamehaven"
NGINX_ENABLED="/etc/nginx/sites-enabled/gamehaven"

# Check if sites-available exists (Debian/Ubuntu style)
if [ -d "/etc/nginx/sites-available" ]; then
    CONF_PATH="$NGINX_CONF"
    ENABLE_PATH="$NGINX_ENABLED"
else
    # RHEL/CentOS style
    CONF_PATH="/etc/nginx/conf.d/gamehaven.conf"
    ENABLE_PATH=""
fi

echo -e "${CYAN}Creating nginx configuration...${NC}"

sudo tee "$CONF_PATH" > /dev/null << NGINXCONF
# GameHaven Reverse Proxy Configuration
# Generated by setup-nginx.sh

server {
    listen 80;
    server_name ${DOMAIN};

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Logging
    access_log /var/log/nginx/gamehaven.access.log;
    error_log /var/log/nginx/gamehaven.error.log;

    # Main application
    location / {
        proxy_pass http://127.0.0.1:${APP_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 86400;
    }

    # API Gateway (Kong)
    location /api/ {
        rewrite ^/api/(.*)\$ /\$1 break;
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # Studio (optional): served at https://<domain>/studio/
    # This avoids needing to expose a separate port over HTTPS.
    location /studio/ {
        rewrite ^/studio/(.*)\$ /\$1 break;
        proxy_pass http://127.0.0.1:${STUDIO_PORT:-3001};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
    }
}
NGINXCONF

echo -e "${GREEN}✓${NC} Nginx configuration created"

# Enable site (Debian/Ubuntu)
if [ -n "$ENABLE_PATH" ]; then
    sudo rm -f "$ENABLE_PATH"
    sudo ln -s "$CONF_PATH" "$ENABLE_PATH"
    
    # Disable default site if it exists
    if [ -f "/etc/nginx/sites-enabled/default" ]; then
        sudo rm -f "/etc/nginx/sites-enabled/default"
    fi
fi

# Test nginx configuration
echo -e "${CYAN}Testing nginx configuration...${NC}"
if sudo nginx -t; then
    echo -e "${GREEN}✓${NC} Nginx configuration valid"
else
    echo -e "${RED}Error: Invalid nginx configuration${NC}"
    exit 1
fi

# Restart nginx
echo -e "${CYAN}Restarting nginx...${NC}"
sudo systemctl restart nginx
sudo systemctl enable nginx
echo -e "${GREEN}✓${NC} Nginx restarted and enabled"

# Setup SSL with Certbot
if [[ "$SETUP_SSL" =~ ^[Yy] ]]; then
    echo ""
    echo -e "${BOLD}━━━ Setting Up SSL ━━━${NC}"
    echo ""
    
    # Install certbot
    if ! command -v certbot &> /dev/null; then
        echo -e "${CYAN}Installing certbot...${NC}"
        if [ "$PKG_MGR" = "apt" ]; then
            sudo apt-get install -y certbot python3-certbot-nginx
        elif [ "$PKG_MGR" = "dnf" ]; then
            sudo dnf install -y certbot python3-certbot-nginx
        else
            sudo yum install -y certbot python3-certbot-nginx
        fi
        echo -e "${GREEN}✓${NC} Certbot installed"
    else
        echo -e "${GREEN}✓${NC} Certbot already installed"
    fi
    
    # Get email for Let's Encrypt
    read -p "$(echo -e "${BLUE}?${NC} Email for Let's Encrypt notifications: ")" LE_EMAIL
    
    if [ -z "$LE_EMAIL" ]; then
        echo -e "${YELLOW}Skipping SSL setup - email required${NC}"
    else
        echo -e "${CYAN}Obtaining SSL certificate...${NC}"
        
        # Run certbot
        sudo certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --email "$LE_EMAIL" --redirect
        
        echo -e "${GREEN}✓${NC} SSL certificate obtained and configured"
        
        # Setup auto-renewal
        echo -e "${CYAN}Setting up auto-renewal...${NC}"
        (sudo crontab -l 2>/dev/null; echo "0 12 * * * /usr/bin/certbot renew --quiet") | sudo crontab -
        echo -e "${GREEN}✓${NC} Auto-renewal configured"
    fi
fi

# Update .env with new URLs if SSL was set up
if [[ "$SETUP_SSL" =~ ^[Yy] ]] && [ -n "$LE_EMAIL" ]; then
    echo ""
    echo -e "${CYAN}Updating configuration with HTTPS URLs...${NC}"
    
        # Update SITE_URL and API_EXTERNAL_URL in .env
    if [ -f .env ]; then
        sed -i "s|^SITE_URL=.*|SITE_URL=\"https://${DOMAIN}\"|" .env
        sed -i "s|^API_EXTERNAL_URL=.*|API_EXTERNAL_URL=\"https://${DOMAIN}/api\"|" .env
        echo -e "${GREEN}✓${NC} Updated .env with HTTPS URLs"
        
        echo -e "${CYAN}Restarting containers with new config...${NC}"
        docker compose down
        docker compose up -d
        echo -e "${GREEN}✓${NC} Containers restarted"
    fi
fi

# Print summary
echo ""
echo -e "${CYAN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}             ${BOLD}${GREEN}Nginx Setup Complete!${NC}                         ${CYAN}║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

if [[ "$SETUP_SSL" =~ ^[Yy] ]] && [ -n "$LE_EMAIL" ]; then
    echo -e "  ${BOLD}Your site is available at:${NC}      ${GREEN}https://${DOMAIN}${NC}"
    echo -e "  ${BOLD}Supabase Studio:${NC}                ${GREEN}https://${DOMAIN}/studio/${NC}"
else
    echo -e "  ${BOLD}Your site is available at:${NC}      ${GREEN}http://${DOMAIN}${NC}"
    echo -e "  ${BOLD}Supabase Studio:${NC}                ${GREEN}http://${DOMAIN}/studio/${NC}"
fi

echo ""
echo -e "${BOLD}Useful Commands:${NC}"
echo -e "  Test nginx:     ${YELLOW}sudo nginx -t${NC}"
echo -e "  Reload nginx:   ${YELLOW}sudo systemctl reload nginx${NC}"
echo -e "  View logs:      ${YELLOW}sudo tail -f /var/log/nginx/gamehaven.*.log${NC}"
echo -e "  Renew SSL:      ${YELLOW}sudo certbot renew${NC}"
echo ""
