#!/bin/bash
#
# Setup Nginx reverse proxy with optional SSL via Certbot
# This script installs nginx and configures it to proxy to the GameHaven app
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'
BOLD='\033[1m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/.."

echo ""
echo -e "${CYAN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}          ${BOLD}Nginx Reverse Proxy Setup${NC}                         ${CYAN}║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Load config if available
if [ -f .env ]; then
    # shellcheck disable=SC1091
    source .env
fi

# Prompt for domain
read -p "$(echo -e "${BLUE}?${NC} Enter your domain name (e.g., games.example.com): ")" DOMAIN

if [ -z "$DOMAIN" ]; then
    echo -e "${RED}Error: Domain is required${NC}"
    exit 1
fi

# Get app port
APP_PORT=${APP_PORT:-3000}
read -p "$(echo -e "${BLUE}?${NC} App port [${APP_PORT}]: ")" INPUT_PORT
APP_PORT=${INPUT_PORT:-$APP_PORT}

# Ask about SSL
read -p "$(echo -e "${BLUE}?${NC} Setup SSL with Let's Encrypt? (y/n) [y]: ")" SETUP_SSL
SETUP_SSL=${SETUP_SSL:-y}

# Detect package manager
if command -v apt-get &> /dev/null; then
    PKG_MGR="apt"
elif command -v dnf &> /dev/null; then
    PKG_MGR="dnf"
elif command -v yum &> /dev/null; then
    PKG_MGR="yum"
else
    echo -e "${RED}Error: Unsupported package manager. Please install nginx manually.${NC}"
    exit 1
fi

echo ""
echo -e "${BOLD}━━━ Installing Nginx ━━━${NC}"
echo ""

# Install nginx
if ! command -v nginx &> /dev/null; then
    echo -e "${CYAN}Installing nginx...${NC}"
    if [ "$PKG_MGR" = "apt" ]; then
        sudo apt-get update
        sudo apt-get install -y nginx
    elif [ "$PKG_MGR" = "dnf" ]; then
        sudo dnf install -y nginx
    else
        sudo yum install -y nginx
    fi
    echo -e "${GREEN}✓${NC} Nginx installed"
else
    echo -e "${GREEN}✓${NC} Nginx already installed"
fi

# Create nginx config
echo ""
echo -e "${BOLD}━━━ Configuring Nginx ━━━${NC}"
echo ""

NGINX_CONF="/etc/nginx/sites-available/gamehaven"
NGINX_ENABLED="/etc/nginx/sites-enabled/gamehaven"

# Check if sites-available exists (Debian/Ubuntu style)
if [ -d "/etc/nginx/sites-available" ]; then
    CONF_PATH="$NGINX_CONF"
    ENABLE_PATH="$NGINX_ENABLED"
else
    # RHEL/CentOS style
    CONF_PATH="/etc/nginx/conf.d/gamehaven.conf"
    ENABLE_PATH=""
fi

echo -e "${CYAN}Creating nginx configuration...${NC}"

sudo tee "$CONF_PATH" > /dev/null << NGINXCONF
# GameHaven Reverse Proxy Configuration
# Generated by setup-nginx.sh

server {
    listen 80;
    server_name ${DOMAIN};

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Logging
    access_log /var/log/nginx/gamehaven.access.log;
    error_log /var/log/nginx/gamehaven.error.log;

    # Main application
    location / {
        proxy_pass http://127.0.0.1:${APP_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 86400;
    }

    # API Gateway (Kong)
    location /api/ {
        rewrite ^/api/(.*)\$ /\$1 break;
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # Studio: redirect /studio to /studio/ for consistency
    location = /studio {
        return 301 \$scheme://\$host/studio/;
    }

    # Studio proxy
    location /studio/ {
        rewrite ^/studio/(.*)\$ /\$1 break;
        proxy_pass http://127.0.0.1:${STUDIO_PORT:-3001};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
    }

    # Studio internal routes (/project/, etc.)
    location /project/ {
        proxy_pass http://127.0.0.1:${STUDIO_PORT:-3001};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
    }
}
NGINXCONF

echo -e "${GREEN}✓${NC} Nginx configuration created"

# Enable site (Debian/Ubuntu)
if [ -n "$ENABLE_PATH" ]; then
    sudo rm -f "$ENABLE_PATH"
    sudo ln -s "$CONF_PATH" "$ENABLE_PATH"
    
    # Disable default site if it exists
    if [ -f "/etc/nginx/sites-enabled/default" ]; then
        sudo rm -f "/etc/nginx/sites-enabled/default"
    fi
fi

# Test nginx configuration
echo -e "${CYAN}Testing nginx configuration...${NC}"
if sudo nginx -t; then
    echo -e "${GREEN}✓${NC} Nginx configuration valid"
else
    echo -e "${RED}Error: Invalid nginx configuration${NC}"
    exit 1
fi

# Restart nginx
echo -e "${CYAN}Restarting nginx...${NC}"
sudo systemctl restart nginx
sudo systemctl enable nginx
echo -e "${GREEN}✓${NC} Nginx restarted and enabled"

# Setup SSL with Certbot
if [[ "$SETUP_SSL" =~ ^[Yy] ]]; then
    echo ""
    echo -e "${BOLD}━━━ Setting Up SSL ━━━${NC}"
    echo ""
    
    # Install certbot
    if ! command -v certbot &> /dev/null; then
        echo -e "${CYAN}Installing certbot...${NC}"
        if [ "$PKG_MGR" = "apt" ]; then
            sudo apt-get install -y certbot python3-certbot-nginx
        elif [ "$PKG_MGR" = "dnf" ]; then
            sudo dnf install -y certbot python3-certbot-nginx
        else
            sudo yum install -y certbot python3-certbot-nginx
        fi
        echo -e "${GREEN}✓${NC} Certbot installed"
    else
        echo -e "${GREEN}✓${NC} Certbot already installed"
    fi
    
    # Get email for Let's Encrypt
    read -p "$(echo -e "${BLUE}?${NC} Email for Let's Encrypt notifications: ")" LE_EMAIL
    
    if [ -z "$LE_EMAIL" ]; then
        echo -e "${YELLOW}Skipping SSL setup - email required${NC}"
    else
        echo -e "${CYAN}Obtaining SSL certificate...${NC}"
        
        # Run certbot
        sudo certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --email "$LE_EMAIL" --redirect
        
        echo -e "${GREEN}✓${NC} SSL certificate obtained and configured"
        
        # Patch SSL server block(s) to include /api and /studio location blocks.
        # We'll create a separate include file to avoid complex regex patching.
        echo -e "${CYAN}Creating SSL proxy locations include file...${NC}"

        SSL_INCLUDE_FILE="/etc/nginx/snippets/gamehaven-proxy-locations.conf"
        sudo mkdir -p /etc/nginx/snippets

        sudo tee "$SSL_INCLUDE_FILE" > /dev/null << SSLLOCATIONS
# GameHaven proxy locations - included in SSL server blocks
# Generated by setup-nginx.sh

# API Gateway (Kong)
location /api/ {
    rewrite ^/api/(.*)\$ /\$1 break;
    proxy_pass http://127.0.0.1:8000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
}

# Studio redirect
location = /studio {
    return 301 \$scheme://\$host/studio/;
}

# Studio proxy
location /studio/ {
    rewrite ^/studio/(.*)\$ /\$1 break;
    proxy_pass http://127.0.0.1:${STUDIO_PORT:-3001};
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_read_timeout 86400;
}

# Studio internal routes - these are where Studio redirects internally
location /project/ {
    proxy_pass http://127.0.0.1:${STUDIO_PORT:-3001};
    proxy_http_version 1.1;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_read_timeout 86400;
}
SSLLOCATIONS

        echo -e "${GREEN}✓${NC} Created ${YELLOW}${SSL_INCLUDE_FILE}${NC}"

        # Function to patch a single SSL vhost file
        patch_ssl_vhost_file() {
            local FILE="$1"
            if [ ! -f "$FILE" ]; then
                return 0
            fi

            # Check if file contains SSL config for our domain
            if ! grep -q "listen 443 ssl" "$FILE" && ! grep -q "listen \[::\]:443 ssl" "$FILE"; then
                return 0
            fi

            # Remove Certbot's catch-all 404 if present
            if grep -q "return 404; # managed by Certbot" "$FILE"; then
                sudo sed -i '/return 404; # managed by Certbot/d' "$FILE"
                echo -e "${GREEN}✓${NC} Removed Certbot 404 catch-all from: ${YELLOW}${FILE}${NC}"
            fi

            # Check if include is already present
            if grep -q "include.*gamehaven-proxy-locations.conf" "$FILE"; then
                echo -e "${GREEN}✓${NC} Proxy locations already included in: ${YELLOW}${FILE}${NC}"
                return 0
            fi

            # Check if individual blocks are already present (from previous patching attempts)
            if grep -q "# API Gateway (Kong) - added by setup-nginx.sh" "$FILE"; then
                echo -e "${YELLOW}!${NC} Legacy proxy blocks found in: ${YELLOW}${FILE}${NC}"
                echo -e "  Consider removing them manually and re-running this script."
                return 0
            fi

            # Insert include directive before the closing brace of the server block
            # We find the last closing brace and insert before it
            sudo python3 << PYSCRIPT
import re

path = "$FILE"
include_line = "    include /etc/nginx/snippets/gamehaven-proxy-locations.conf;\n"

with open(path, "r", encoding="utf-8") as f:
    content = f.read()

# Find the SSL server block and insert include before its closing brace
# Look for server blocks with listen 443
server_pattern = r'(server\s*\{[^{}]*listen\s+(?:\[::\]:)?443\s+ssl[^{}]*(?:\{[^{}]*\}[^{}]*)*)'
matches = list(re.finditer(server_pattern, content, re.DOTALL))

if not matches:
    # Simpler approach: find any server block with 443 ssl and add include before last }
    lines = content.split('\n')
    in_ssl_server = False
    brace_count = 0
    insert_line = -1
    
    for i, line in enumerate(lines):
        if 'listen' in line and '443' in line and 'ssl' in line:
            in_ssl_server = True
        if in_ssl_server:
            brace_count += line.count('{') - line.count('}')
            if brace_count == 0 and '}' in line:
                insert_line = i
                in_ssl_server = False
                break
    
    if insert_line > 0:
        lines.insert(insert_line, include_line.rstrip())
        content = '\n'.join(lines)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Inserted include directive into: {path}")
    else:
        print(f"Could not find SSL server block in: {path}")
else:
    # Insert before the last closing brace we can find
    last_brace = content.rfind('}')
    if last_brace > 0:
        content = content[:last_brace] + include_line + content[last_brace:]
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Inserted include directive into: {path}")
PYSCRIPT

            # Test nginx config after patching this file
            if sudo nginx -t 2>/dev/null; then
                echo -e "${GREEN}✓${NC} Patched and validated: ${YELLOW}${FILE}${NC}"
            else
                echo -e "${RED}!${NC} Nginx test failed after patching: ${YELLOW}${FILE}${NC}"
                echo -e "  Reverting change..."
                # Remove the include line we just added
                sudo sed -i '/include.*gamehaven-proxy-locations.conf/d' "$FILE"
                echo -e "${YELLOW}!${NC} Reverted. You may need to add proxy locations manually."
            fi
        }

        # Patch the primary config path we created
        patch_ssl_vhost_file "$CONF_PATH" || true

        # Patch any Certbot-generated SSL vhost files for this domain
        SSL_CANDIDATES=$(sudo grep -RIl "server_name\s\+${DOMAIN};" /etc/nginx 2>/dev/null | head -n 50 || true)
        while IFS= read -r f; do
            [ -z "$f" ] && continue
            # Only patch candidates that look like vhost config files
            case "$f" in
                *.conf|*/sites-available/*|*/sites-enabled/*)
                    patch_ssl_vhost_file "$f" || true
                    ;;
            esac
        done <<< "$SSL_CANDIDATES"

        # Final nginx test and reload
        echo ""
        if sudo nginx -t; then
            sudo systemctl reload nginx
            echo -e "${GREEN}✓${NC} Nginx reloaded with SSL + proxy configuration"
        else
            echo -e "${RED}Error: Final nginx config test failed.${NC}"
            echo -e "  Check ${YELLOW}/etc/nginx/snippets/gamehaven-proxy-locations.conf${NC}"
            echo -e "  and your site configs in ${YELLOW}/etc/nginx/sites-enabled/${NC}"
            echo ""
            echo -e "${BOLD}Manual fix:${NC}"
            echo -e "  1. Edit your SSL server block and add this line inside it:"
            echo -e "     ${CYAN}include /etc/nginx/snippets/gamehaven-proxy-locations.conf;${NC}"
            echo -e "  2. Run: ${YELLOW}sudo nginx -t && sudo systemctl reload nginx${NC}"
        fi
        
        # Setup auto-renewal
        echo -e "${CYAN}Setting up auto-renewal...${NC}"
        (sudo crontab -l 2>/dev/null | grep -v certbot; echo "0 12 * * * /usr/bin/certbot renew --quiet") | sudo crontab -
        echo -e "${GREEN}✓${NC} Auto-renewal configured"
    fi
fi

# Update .env with new URLs if SSL was set up
if [[ "$SETUP_SSL" =~ ^[Yy] ]] && [ -n "$LE_EMAIL" ]; then
    echo ""
    echo -e "${CYAN}Updating configuration with HTTPS URLs...${NC}"
    
        # Update SITE_URL and API_EXTERNAL_URL in .env
    if [ -f .env ]; then
        sed -i "s|^SITE_URL=.*|SITE_URL=\"https://${DOMAIN}\"|" .env
        sed -i "s|^API_EXTERNAL_URL=.*|API_EXTERNAL_URL=\"https://${DOMAIN}/api\"|" .env
        echo -e "${GREEN}✓${NC} Updated .env with HTTPS URLs"
        
        echo -e "${CYAN}Restarting containers with new config...${NC}"
        docker compose down
        docker compose up -d
        echo -e "${GREEN}✓${NC} Containers restarted"
    fi
fi

# Print summary
echo ""
echo -e "${CYAN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}             ${BOLD}${GREEN}Nginx Setup Complete!${NC}                         ${CYAN}║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

if [[ "$SETUP_SSL" =~ ^[Yy] ]] && [ -n "$LE_EMAIL" ]; then
    echo -e "  ${BOLD}Your site is available at:${NC}      ${GREEN}https://${DOMAIN}${NC}"
    echo -e "  ${BOLD}Supabase Studio:${NC}                ${GREEN}https://${DOMAIN}/studio/${NC}"
else
    echo -e "  ${BOLD}Your site is available at:${NC}      ${GREEN}http://${DOMAIN}${NC}"
    echo -e "  ${BOLD}Supabase Studio:${NC}                ${GREEN}http://${DOMAIN}/studio/${NC}"
fi

echo ""
echo -e "${BOLD}Useful Commands:${NC}"
echo -e "  Test nginx:     ${YELLOW}sudo nginx -t${NC}"
echo -e "  Reload nginx:   ${YELLOW}sudo systemctl reload nginx${NC}"
echo -e "  View logs:      ${YELLOW}sudo tail -f /var/log/nginx/gamehaven.*.log${NC}"
echo -e "  Renew SSL:      ${YELLOW}sudo certbot renew${NC}"
echo ""
